export const UNMOUNT = 'UNMOUNT';
export const RESETPASSWORD_LOADER = 'RESETPASSWORD_LOADER';
export const RESETID_SUCCESS = 'RESETID_SUCCESS';
export const RESETPASSWORD_SUCCESS = 'RESETPASSWORD_SUCCESS';
